apps/cms/urls.py
#! /usr/bin/python

from django.urls import path

from apps.cms import views

app_name = 'cms'

urlpatterns = [
    path('', views.index, name='index'),
    path('write_news/', views.WriteNewsView.as_view(), name='write_news'),
    path('news_category/', views.news_category, name='news_category'),
    path('add_news_category/', views.add_news_category,
         name='add_news_category'),
    path('edit_news_category/', views.edit_news_category,
         name='edit_news_category'),
    path('delete_news_category/', views.delete_news_category,
         name='delete_news_category'),
    path('upload_file/', views.upload_file,
         name='upload_file'),
]

apps/xfzauth/urls.py
#! /usr/bin/python
from django.urls import path
from . import views

app_name = 'xfzauth'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('img_captcha/', views.img_captcha, name='img_captcha'),
    path('sms_captcha/', views.sms_captcha, name='sms_captcha'),
    path('register/', views.register, name='register'),
    path('cache_test/', views.cache_test, name='cache_test'),
]

xfz/urls.py
from django.urls import path, include
from apps.news import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('', views.index, name='index'),
                  path('search/', views.search, name='search'),
                  path('news/', include("apps.news.urls")),
                  path('cms/', include('apps.cms.urls')),
                  path('account/', include("apps.xfzauth.urls")),
                  path('course/', include('apps.course.urls')),
                  path('payinfo/', include('apps.payinfo.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/cms/models.py
from django.db import models

# Create your models here.

apps/cms/forms.py
#! /usr/bin/python
from apps.forms import FormMixin
from django import forms


class EditNewsCategoryForm(forms.Form, FormMixin):
    pk = forms.IntegerField(error_messages={"required": "必须传入分类的id！"})
    name = forms.CharField(max_length=100)

apps/cms/views.py
from django.shortcuts import render
from django.contrib.admin.views.decorators import staff_member_required
from django.views.generic import View
from django.views.decorators.http import require_GET, require_POST
from apps.news.models import NewsCategory
from utils import restful
from .forms import EditNewsCategoryForm
import os
from django.conf import settings


# Create your views here.
@staff_member_required(login_url='index')
def index(request):
    return render(request, 'cms/index.html')


class WriteNewsView(View):
    def get(self, request):
        categories = NewsCategory.objects.all()
        context = {
            'categories': categories
        }
        return render(request, 'cms/write_news.html', context=context)


@require_GET
def news_category(request):
    categories = NewsCategory.objects.all()
    context = {
        'categories': categories
    }
    return render(request, 'cms/news_category.html', context=context)


@require_POST
def add_news_category(request):
    name = request.POST.get('name')
    exists = NewsCategory.objects.filter(name=name).exists()
    if not exists:
        NewsCategory.objects.create(name=name)
        return restful.ok(message='添加成功')
    else:
        return restful.params_error(message="该分类已经存在")


@require_POST
def edit_news_category(request):
    form = EditNewsCategoryForm(request.POST)
    if form.is_valid():
        pk = form.cleaned_data.get('pk')
        name = form.cleaned_data.get('name')
        try:
            NewsCategory.objects.filter(pk=pk).update(name=name)
            return restful.ok(message="修改完成")
        except:
            return restful.params_error(message="该分类不存在")
    else:
        return restful.params_error(message=form.get_errors())


@require_POST
def delete_news_category(request):
    pk = request.POST.get('pk')
    try:
        NewsCategory.objects.filter(pk=pk).delete()
        return restful.ok()
    except:
        return restful.unauth(message="该分类不存在")


@require_POST
def upload_file(request):
    file = request.FILES.get('file')
    name = file.name
    with open(os.path.join(settings.MEDIA_ROOT, name), 'wb') as fp:
        for chunk in file.chunks():
            fp.write(chunk)
    url = request.build_absolute_uri(settings.MEDIA_URL + name)
    return restful.ok(data={'url': url})

front/templates/cms/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock %} | 小饭桌管理系统</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
          name="viewport">
    <link rel="stylesheet"
          href="{% static 'adminlte/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet"
          href="{% static 'adminlte/bower_components/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet"
          href="{% static 'adminlte/bower_components/Ionicons/css/ionicons.min.css' %}">
    <link rel="stylesheet"
          href="{% static 'adminlte/dist/css/AdminLTE.min.css' %}">
    <link rel="stylesheet"
          href="{% static 'adminlte/dist/css/skins/_all-skins.min.css' %}">
    <link rel="stylesheet"
          href="{% static 'adminlte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css' %}">
    <link rel="stylesheet" href="{% static 'sweetalert/sweetalert.css' %}">
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <script src="{% static 'sweetalert/sweetalert.min.js' %}"></script>
    <script src="{% static 'adminlte/bower_components/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'adminlte/bower_components/jquery-ui/jquery-ui.min.js' %}"></script>
    <script src="{% static 'adminlte/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'adminlte/dist/js/adminlte.min.js' %}"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="{% static 'adminlte/dist/js/pages/dashboard.js' %}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'adminlte/dist/js/demo.js' %}"></script>
    <script src="{% static 'js/message.min.js' %}"></script>
    <script src="{% static 'js/xfzalert.min.js' %}"></script>
    <script src="{% static 'js/xfzajax.min.js' %}"></script>
    <![endif]-->
    {% block head %}{% endblock %}

</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
    <header class="main-header">
        <a href="index2.html" class="logo">
            <span class="logo-mini"><b>C</b>MS</span>
            <span class="logo-lg"><b>小饭桌</b>后台管理系统</span>
        </a>
        <nav class="navbar navbar-static-top">
            <a href="#" class="sidebar-toggle" data-toggle="push-menu"
               role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>

            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle"
                           data-toggle="dropdown">
                            <img src="{% static 'adminlte/dist/img/avatar5.png' %}"
                                 class="user-image" alt="User Image">
                            <span class="hidden-xs">李晨阳</span>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- User image -->
                            <li class="user-header">
                                <img src="{% static 'adminlte/dist/img/avatar5.png' %}"
                                     class="img-circle" alt="User Image">

                                <p>
                                    李晨阳
                                    <small>运维开发工程师</small>
                                </p>
                            </li>

                            <!-- Menu Footer-->
                            <li class="user-footer">
                                <div class="pull-left">
                                    <a href="#"
                                       class="btn btn-default btn-flat">个人中心</a>
                                </div>
                                <div class="pull-right">
                                    <a href="#"
                                       class="btn btn-default btn-flat">退出登录</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <!-- Sidebar user panel -->
            <div class="user-panel">
                <div class="pull-left image">
                    <img src="{% static 'adminlte/dist/img/avatar5.png' %}"
                         class="img-circle"
                         alt="User Image">
                </div>
                <div class="pull-left info">
                    <p>李晨阳</p>
                    <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                </div>
            </div>
            <!-- search form -->
            <form action="#" method="get" class="sidebar-form">
                <div class="input-group">
                    <input type="text" name="q" class="form-control"
                           placeholder="查找">
                    <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn"
                        class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
                </div>
            </form>
            <!-- /.search form -->
            <!-- sidebar menu: : style can be found in sidebar.less -->
            <ul class="sidebar-menu" data-widget="tree">
                <li class="active">
                    <a href="{% url 'cms:index' %}">
                        <i class="fa fa-home"></i>
                        <span>首页</span>
                    </a>
                </li>
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-dashboard"></i>
                        <span>新闻管理</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="active">
                            <a href="{% url 'cms:write_news' %}">
                                <i class="fa fa-edit"></i>
                                <span>发布新闻</span>
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'cms:news_category' %}">
                                <i class="fa fa-tag"></i>
                                <span>新闻分类</span>
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </section>
        <!-- /.sidebar -->
    </aside>
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            {% block content-header %}{% endblock %}
        </section>

        <!-- Main content -->
        <section class="content">
            {% block content %}{% endblock %}
        </section>
        <!-- /.content -->
    </div>
    <footer class="main-footer">
        <div class="pull-right hidden-xs">
            Made by<b> Lichy</b>
        </div>
        <strong>小饭桌</strong>后台管理系统
    </footer>
</div>


</body>
</html>

front/templates/cms/index.html
{% extends 'cms/base.html' %}

{% block title %}首页{% endblock %}
{% block content-header %}
    <h1>欢迎来到小饭桌CMS管理系统</h1>
{% endblock %}

front/templates/cms/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 2 | Log in</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href={% static "adminlte/bower_components/bootstrap/dist/css/bootstrap.min.css" %}>
    <!-- Font Awesome -->
    <link rel="stylesheet" href={% static "adminlte/bower_components/font-awesome/css/font-awesome.min.css" %}>
    <!-- Ionicons -->
    <link rel="stylesheet" href={% static "adminlte/bower_components/Ionicons/css/ionicons.min.css" %}>
    <!-- Theme style -->
    <link rel="stylesheet" href={% static "adminlte/dist/css/AdminLTE.min.css" %}>
    <!-- iCheck -->
    <link rel="stylesheet" href={% static "adminlte/plugins/iCheck/square/blue.css" %}>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition login-page">
<div class="login-box">
    <div class="login-logo">
        <a href="#"><b>小饭桌管理系统</b></a>
    </div>
    <!-- /.login-logo -->
    <div class="login-box-body">
        <p class="login-box-msg">请登录</p>

        <form action="{% url 'xfzauth:login' %}" method="post">
            {% csrf_token %}
            <div class="form-group has-feedback">
                <input type="text" class="form-control" name="telephone" placeholder="手机号码">
                <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
            </div>
            <div class="form-group has-feedback">
                <input type="password" class="form-control" name="password" placeholder="密码">
                <span class="glyphicon glyphicon-lock form-control-feedback"></span>
            </div>
            <div class="row">
                <div class="col-xs-8">
                    <div class="checkbox icheck">
                        <label>
                            <input type="checkbox" name="remember" value="1"> 记住我
                        </label>
                    </div>
                </div>
                <!-- /.col -->
                <div class="col-xs-4">
                    <button type="submit" class="btn btn-primary btn-block btn-flat">登录</button>
                </div>
                <!-- /.col -->
            </div>
        </form>


    </div>
    <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

<!-- jQuery 3 -->
<script src={% static "adminlte/bower_components/jquery/dist/jquery.min.js" %}></script>
<!-- Bootstrap 3.3.7 -->
<script src={% static "adminlte/bower_components/bootstrap/dist/js/bootstrap.min.js" %}></script>
<!-- iCheck -->
<script src={% static "adminlte/plugins/iCheck/icheck.min.js" %}></script>
<script>
    $(function () {
        $('input').iCheck({
            checkboxClass: 'icheckbox_square-blue',
            radioClass: 'iradio_square-blue',
            increaseArea: '20%' /* optional */
        });
    });
</script>
</body>
</html>

front/templates/cms/news_category.html
{% extends 'cms/base.html' %}

{% block title %}
    新闻分类
{% endblock %}

{% block head %}
    <script src="{% static 'js/news_category.min.js' %}"></script>
{% endblock %}

{% block content-header %}
    <h1>新闻分类</h1>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                    <button class="btn btn-primary pull-right" id="add-btn">
                        添加分类
                    </button>
                </div>
                <div class="box-body">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th>分类名称</th>
                            <th>新闻数量</th>
                            <th>操作</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for category in categories %}
                            <tr data-pk="{{ category.pk }}"
                                data-name="{{ category.name }}"
                            >
                                <td>{{ category.name }}</td>
                                <td>20</td>
                                <td>
                                    <button class="btn btn-warning btn-xs edit-btn">
                                        编辑
                                    </button>
                                    <button class="btn btn-danger btn-xs delete-btn">
                                        删除
                                    </button>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

front/templates/cms/write_news.html
{% extends 'cms/base.html' %}
{% block head %}
    <script src="{% static 'js/write_news.min.js' %}"></script>
{% endblock %}
{% block title %}发布新闻{% endblock %}
{% block content-header %}
    <h1>发布新闻</h1>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                    <h3 class="box-title">在此次填写发布内容</h3>
                </div>
                <form action="" class="form">
                    <div class="box-body">
                        <div class="form-group">
                            <label for="title-form">标题</label>
                            <input class="form-control" type="text" name="title"
                                   id="title-form">
                        </div>
                        <div class="form-group">
                            <label for="category-form">分类</label>
                            <select class="form-control" name="category"
                                    id="category-form">
                                {% for category in categories %}
                                    <option value="{{ category.pk }}">{{ category.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="desc-form">描述信息</label>
                            <input class="form-control" type="text" name="desc"
                                   id="desc-form">
                        </div>
                        <div class="form-group">
                            <label for="thumbnail-form">缩略图</label>
                            <div class="input-group">
                                <input type="text" class="form-control"
                                       id="thumbnail-form" name="thumbnail">
                                <span class="input-group-btn">
                                    <label class="btn btn-default btn-file">
                                        <input hidden type="file"
                                               class="btn btn-default"
                                               id="thumbnail-btn"
                                        >上传图片
                                    </label>
                                </span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="content-form">内容</label>
                            <textarea class="form-control" id="content-form"
                                      cols="30" rows="10">
                            </textarea>
                        </div>
                    </div>
                    <div class="box-footer">
                        <button class="btn btn-primary pull-right">发布新闻</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}