apps/cms/urls.py
#! /usr/bin/python

from django.urls import path

from apps.cms import views

app_name = 'cms'

urlpatterns = [
    path('', views.index, name='index'),
    path('write_news/', views.WriteNewsView.as_view(), name='write_news'),
    path('news_category/', views.news_category, name='news_category'),
    path('add_news_category/', views.add_news_category,
         name='add_news_category'),
    path('edit_news_category/', views.edit_news_category,
         name='edit_news_category'),
    path('delete_news_category/', views.delete_news_category,
         name='delete_news_category'),
    path('upload_file/', views.upload_file,
         name='upload_file'),
]

apps/xfzauth/urls.py
#! /usr/bin/python
from django.urls import path
from . import views

app_name = 'xfzauth'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('img_captcha/', views.img_captcha, name='img_captcha'),
    path('sms_captcha/', views.sms_captcha, name='sms_captcha'),
    path('register/', views.register, name='register'),
    path('cache_test/', views.cache_test, name='cache_test'),
]

xfz/urls.py
from django.urls import path, include
from apps.news import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('', views.index, name='index'),
                  path('search/', views.search, name='search'),
                  path('news/', include("apps.news.urls")),
                  path('cms/', include('apps.cms.urls')),
                  path('account/', include("apps.xfzauth.urls")),
                  path('course/', include('apps.course.urls')),
                  path('payinfo/', include('apps.payinfo.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

front/templates/base/front_base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'js/message.min.js' %}"></script>
    <script src="{% static 'js/xfzajax.min.js' %}"></script>
    <script src="{% static 'js/front_base.min.js' %}"></script>
    <script></script>
    <link rel="stylesheet" href="//at.alicdn.com/t/font_1688767_xbonih3c24.css">
    <link rel="stylesheet" href="{% static 'css/common/auth.min.css' %}">
    {% block head %}{% endblock %}
</head>

<body>
<header class="header">
    <div class="container">
        {% csrf_token %}
        <div class="logo-box">
            <a href="./"></a>
        </div>
        <ul class="nav">
            <li class="active"><a href="./">创业资讯</a></li>
            <li><a href="./">创业课堂</a></li>
            <li><a href="./">付费咨询</a></li>
            <li><a href="./">搜索</a></li>
        </ul>
        <div class="auth-box">
            <i class="icon-person iconfont"></i>
            {% if user.is_authenticated %}
            <a href="#" class="authenticated-box">{{ user.username }}</a>
            <div class="user-more-box">
                <i class="triangle"></i>
                {% if user.is_staff %}
                <a href="{% url 'cms:index' %}">管理系统</a>
                {% endif %}
                <a href="{% url 'xfzauth:logout' %}">退出登录</a>
            </div>
            {% else %}
            <a href=" #" class="signin-btn">登录</a> /
            <a href="#" class="signup-btn">注册</a>
            {% endif %}
        </div>
    </div>
</header>
{% block main %}{% endblock %}
<footer class="footer">
    <div class="top-group">
        <div class="top-inner-group">
            <div class="logo-box">

            </div>
            <div class="detail-group">
                <div class="line1">
                    <ul class="links">
                        <li><a href="#">关于小饭桌</a></li>
                        <li><a href="#">创业课堂</a></li>
                        <li><a href="#">寻求报道</a></li>
                        <li><a href="#">创业礼包</a></li>
                    </ul>
                    <div class="about-us">
                        <span class="title">关于我们：</span>
                        <ul class="social-group">
                            <li class="weixin">
                                <div class="wx-qrcode">

                                </div>
                                <a href="#" class="text">
                                    xfz008
                                </a>
                            </li>
                            <li class="weibo">
                                <a class="text" href="#">
                                    小饭桌创业课堂
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="line2">
                    <p class="address">北京市朝阳区东三环北路38号院泰康金融大厦</p>
                    <p class="contact">联系方式：400-810-1090</p>
                </div>
            </div>
        </div>
    </div>
    <div class="bottom-group">
        ©2020 北京子木投资顾问有限公司 京ICP备15051289号 | 增值电信业务经营许可证：京B2-20170574
    </div>
</footer>
<div class="mask-wrapper">
    <div class="auth-wrapper">
        <div class="close-wrapper">
                <span class="close-btn icon-close iconfont">

                </span>
        </div>
        <div class="auth-inner-wrapper">
            <div class="scroll-wrapper">
                <div class="signin-group auth-group">
                    <div class="top-group">
                        <span class="title">请登录</span>
                        <a class="switch" href="javascript: void(0);">立即注册></a>
                    </div>
                    <div class="from-group">
                        <div class="input-group">
                            <input type="text" name="telephone"
                                   class="form-control" placeholder="请输入手机号码">
                        </div>
                        <div class="input-group">
                            <input type="password" name="password"
                                   class="form-control" placeholder="请输入密码">
                        </div>
                        <div class="input-group">
                            <label class="remember-label">
                                <input type="checkbox" name="remember"
                                       value="1">记住我
                            </label>
                        </div>
                        <div class="input-group">
                            <input type="submit" class="submit-btn"
                                   value="立即登录">
                        </div>

                    </div>

                </div>
                <div class="signup-group auth-group">
                    <div class="top-group">
                        <span class="title">请注册</span>
                        <a class="switch" href="javascript: void(0);">立即登陆></a>
                    </div>
                    <div class="from-group">
                        <div class="input-group">
                            <input type="text" name="telephone"
                                   class="form-control" placeholder="手机号码">
                        </div>
                        <div class="input-group">
                            <input type="text" name="username"
                                   class="form-control" placeholder="用户名">
                        </div>
                        <div class="input-group">
                            <div class="short-input-group">
                                <input type="text" class="form-control"
                                       name="img_captcha" placeholder="图形验证码">
                            </div>
                            <div class="input-group-addon">
                                <img class="img-captcha"
                                     src="{% url 'xfzauth:img_captcha' %}"
                                     alt=""
                                     style="cursor: pointer;">
                            </div>
                        </div>
                        <div class="input-group">
                            <input type="password" name="password1"
                                   class="form-control" placeholder="密码">
                        </div>
                        <div class="input-group">
                            <input type="password" name="password2"
                                   class="form-control" placeholder="确认密码">
                        </div>
                        <div class="input-group">
                            <div class="short-input-group">
                                <input type="text" class="form-control"
                                       name="sms_captcha" placeholder="短信验证码">
                            </div>
                            <div class="input-group-addon">
                                <span class="sms-captcha-btn">发送验证码</span>
                            </div>
                        </div>
                        <div class="input-group">
                            <input type="submit" class="submit-btn"
                                   value="立即注册">
                        </div>

                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
</body>

</html>